#+OPTIONS: toc:nil
#+STARTUP: showall

* Summary

  We have prepared an alternative environment (on Chameleoncloud) for students developing with the Big Data Stack.
  Chameleon Cloud provides an environment for experimenting with cloud environments.
  Currently, chamelen provide an OpenStack IaaS based on the Liberty release. 
  We do not control Chameleon, and the resource provided are very kindly made available for this class.
  Please be good citizens use the resources responsibly.
  This means no floating ip allocations, a limit of 3 instances per group, and deleting any unused instances.

  There are some differences between FutureSystems OpenStack and Chameleon OpenStack.

  - small pool of floating ips
  - different login usernames (=cc= for all instead of =ubuntu=, =centos=, etc) for the images
  - limited resource availability
  - resource usage is charged to a finite allocation (thus you need to terminate your instances if you do not use them).

** Quotas

   - Instances: 55
   - VCPUs: 110
   - RAM: 220 GB
   - Floating IP: 55
   - Security Groups: 10
   - Volumes: 10
   - 20,000 SUs (see [[https://www.chameleoncloud.org/docs/user-faq/#toc-what-are-the-units-of-an-allocation-and-how-am-i-charged-][here]] for SU details)


* Getting Access

  1. Create an account on [[https://www.chameleoncloud.org/][Chameleon Cloud]]
  2. Send your Chameleon username to bdosspcoursehelp@googlegroups.com
     Note: the subject *MUST* be
     #+BEGIN_EXAMPLE
     Chameleon Cloud Access
     #+END_EXAMPLE
  3. We will then add you to the project for this course. *IMPORTANT*: you will not be able to use Chameleon until you are added. We will reply to your request with a confirmation email.


* Setup instructions

  1. Ssh into =india.futuresystems.org=:
  2. Go to the [[https://openstack.tacc.chameleoncloud.org/dashboard/project/access_and_security/][Chameleon Cloud OpenStack Dashboard]] and download the openrc file
  3. Upload this openrc file to the =india= node
     #+BEGIN_EXAMPLE
     $ scp CH-817724-openrc.sh india.futuresystems.org:~
     #+END_EXAMPLE
  4. Upload upload your india ssh key to your [[https://github.com/settings/ssh][profile on github.com]]
     #+BEGIN_EXAMPLE
     badi@i136 ~ $ cat ~/.ssh/id_rsa.pub
     #+END_EXAMPLE
  5. Source the openrc file (*only* the chameleon openrc file):
     #+BEGIN_EXAMPLE
     badi@i136 ~ $ source ~/CH-817724-openrc.sh
     #+END_EXAMPLE
  6. Load the OpenStack module (same as with kilo on india):
     #+BEGIN_EXAMPLE
     badi@i136 ~ $ module load openstack
     #+END_EXAMPLE

  At this point you the nova commands will control Chameleon.
  For BDS, you will need modify the =.cluster.py= and =ansible.cfg= files to specify the correct Chameleon Cloud image and user:

  2. Use the Chameleon Cloud Ubuntu image by changing =defaults/openstack/image= in =.cluster.py= to =CC-Ubuntu14.04=
     #+BEGIN_EXAMPLE
     (bds) badi@login big-data-stack $ nano .cluster.py
     #+END_EXAMPLE
  3. Change =remote_user= from =ubuntu= to =cc= in =ansible.cfg=
     #+BEGIN_EXAMPLE
     (bds) badi@login big-data-stack $ nano ansible.cfg
     #+END_EXAMPLE

  You can now follow the [[https://github.com/futuresystems/big-data-stack][Big Data Stack Readme]] for starting and deploying your BDS


* Notes

** =apt= related errors

  You may occasionally get an error when one of the tasks calls to apt, either to update the cache or install packages.
  This will likely manifest as a =Failed to fetch= with an =Error 403 Forbidden= error.
  The root cause for this is not yet known, but it seems related to a network saturation issue.
  Nonetheless, the workaround is simple: rerun the playbook that failed.
  This may need to be repeated a few times, but this has been sufficient to resolve the issue when I encounter them.
