---

################################################################################

- name: Provide useful packages
  hosts: all
  become: yes
  tags: install_packages
  tasks:
    - name: Install packages
      yum:
        name: "{{ item.packages }}"
        state: present
      with_items:
        - description: Python development tools
          packages:
            - python
            - python-pip
            - python-virtualenv
            - python-devel
        - description: Version control tools
          packages:
            - git
        - description: Editors
          packages:
            - emacs-nox
            - vim-enhanced
            - nano


################################################################################

- name: Setup users
  hosts: all
  become: yes
  vars:
    public_keys_dir: public_keys
    users_file: users.txt
    users: "{{ lookup('pipe', 'cat ' + users_file).split('\n') }}"
  tags: setup_users
  tasks:

    - name: create users
      user:
        name: "{{ item }}"
        state: present
        createhome: yes
        system: no
      with_items: "{{ users }}"

    - name: allow users to login
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('pipe', 'for f in '+public_keys_dir+'/'+item+'/*; do cat $f;echo;done') }}"
      with_items: "{{ users }}"
